#!/usr/bin/env python3
"""Generate the light and dark Cella SFZ panels with outlined text.

Rack's SVG renderer does not support SVG text elements. This generator uses
fontTools to convert glyphs from the bundled font into path data so the panel
renders identically without depending on fonts installed on the user's system.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont


PANEL_WIDTH = 180
PANEL_HEIGHT = 380


@dataclass(frozen=True)
class Theme:
    filename: str
    background: str
    foreground: str
    input_fill: str
    input_opacity: float
    output_fill: str
    output_opacity: float


THEMES = (
    Theme(
        filename="CellaSFZ.svg",
        background="#909090",
        foreground="#ecedf1",
        input_fill="#ab5b87",
        input_opacity=0.75,
        output_fill="#699b9c",
        output_opacity=0.8,
    ),
    Theme(
        filename="CellaSFZ-dark.svg",
        background="#252626",
        foreground="#f7c5ad",
        input_fill="#723957",
        input_opacity=0.85,
        output_fill="#356468",
        output_opacity=0.9,
    ),
)


@dataclass(frozen=True)
class Label:
    text: str
    x: float
    baseline: float
    size: float
    letter_spacing: float = 0.0


LABELS = (
    Label("CELLA SFZ", 90, 18, 13, 1.8),
    Label("LEVEL", 35, 106, 8),
    Label("OCTAVE", 90, 106, 8),
    Label("TUNE", 145, 106, 8),
    Label("PREV", 55, 215, 7),
    Label("LOAD", 90, 215, 9),
    Label("NEXT", 125, 215, 7),
    Label("V/OCT", 35, 238, 8),
    Label("GATE", 90, 238, 8),
    Label("VELOCITY", 145, 238, 8),
    Label("LEFT / MONO", 62, 304, 8),
    Label("RIGHT", 118, 304, 8),
    Label("CELLA", 90, 375, 7, 4),
)


class OutlinedFont:
    def __init__(self, path: Path) -> None:
        self.font = TTFont(path)
        self.glyph_set = self.font.getGlyphSet()
        self.cmap = self.font.getBestCmap()
        self.advances = self.font["hmtx"].metrics
        self.units_per_em = self.font["head"].unitsPerEm

    def _glyph_name(self, character: str) -> str:
        glyph_name = self.cmap.get(ord(character))
        if glyph_name is None:
            raise ValueError(f"font has no glyph for {character!r}")
        return glyph_name

    def label_paths(self, label: Label) -> Iterable[str]:
        scale = label.size / self.units_per_em
        glyph_names = [self._glyph_name(character) for character in label.text]
        advances = [self.advances[name][0] * scale for name in glyph_names]
        width = sum(advances) + label.letter_spacing * max(0, len(glyph_names) - 1)
        cursor = label.x - width * 0.5

        for glyph_name, advance in zip(glyph_names, advances):
            glyph = self.glyph_set[glyph_name]
            path_pen = SVGPathPen(self.glyph_set, ntos=format_number)
            transform_pen = TransformPen(
                path_pen, (scale, 0.0, 0.0, -scale, cursor, label.baseline)
            )
            glyph.draw(transform_pen)
            commands = path_pen.getCommands()
            if commands:
                yield f'    <path d="{commands}"/>'
            cursor += advance + label.letter_spacing


def format_number(value: float) -> str:
    rounded = f"{value:.4f}".rstrip("0").rstrip(".")
    return "0" if rounded in {"", "-0"} else rounded


def panel_svg(theme: Theme, font: OutlinedFont) -> str:
    label_paths = "\n".join(
        path for label in LABELS for path in font.label_paths(label)
    )
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tools/generate_sfz_panels.py; do not edit directly. -->
<svg xmlns="http://www.w3.org/2000/svg" width="{PANEL_WIDTH}" height="{PANEL_HEIGHT}" viewBox="0 0 {PANEL_WIDTH} {PANEL_HEIGHT}">
  <rect width="{PANEL_WIDTH}" height="{PANEL_HEIGHT}" fill="{theme.background}"/>
  <path d="M0 25h{PANEL_WIDTH}" stroke="{theme.foreground}" stroke-width=".83"/>
  <g fill="{theme.foreground}">
{label_paths}
  </g>
  <g fill="none" stroke="{theme.foreground}" stroke-width=".65" opacity=".8">
    <path d="M18 223h144"/>
    <path d="M35 244v7M90 244v7M145 244v7M62 309v7M118 309v7"/>
  </g>
  <g fill="{theme.input_fill}" opacity="{theme.input_opacity:g}">
    <rect x="18" y="245" width="34" height="40" rx="4"/>
    <rect x="73" y="245" width="34" height="40" rx="4"/>
    <rect x="128" y="245" width="34" height="40" rx="4"/>
  </g>
  <g fill="{theme.output_fill}" opacity="{theme.output_opacity:g}">
    <rect x="45" y="310" width="34" height="40" rx="4"/>
    <rect x="101" y="310" width="34" height="40" rx="4"/>
  </g>
</svg>
'''


def main() -> None:
    repository = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--font",
        type=Path,
        default=repository / "res/fonts/JetBrainsMono-Medium.ttf",
        help="TrueType/OpenType font used to outline labels",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=repository / "res",
        help="directory receiving CellaSFZ.svg and CellaSFZ-dark.svg",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in panels differ from generated output",
    )
    args = parser.parse_args()

    outlined_font = OutlinedFont(args.font)
    if not args.check:
        args.output_dir.mkdir(parents=True, exist_ok=True)
    for theme in THEMES:
        output = args.output_dir / theme.filename
        generated = panel_svg(theme, outlined_font)
        if "<text" in generated or "font-family" in generated:
            raise RuntimeError("Rack panels must contain outlined text only")
        if args.check:
            if not output.is_file() or output.read_text(encoding="utf-8") != generated:
                raise SystemExit(
                    f"{output} is stale; run {Path(__file__).name} to regenerate it"
                )
            print(f"checked {output}")
        else:
            output.write_text(generated, encoding="utf-8")
            print(output)


if __name__ == "__main__":
    main()
